# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test & Build
on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v5

    - name: Set up
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Tests
      run: go test -race ./...

    - name: Lint
      run: "go vet ./..."

    - name: Build
      run: go build ./cmd
